### ISSUE TITLE
サウンドをゲームに取り込む

### ISSUE THREAD

**Issue by ShinoharaRyuga** [VGA-Team2022/idol-road#104]
```yaml
start_date: 2022/11/21
due_date: 2022/12/8
progress: 0.1
parent: 0
```

資料
[ADXにおけるAISAC](https://game.criware.jp/manual/native/adx2/latest/criatom_samples_control_aisac.html)
[AISACコントロール](https://game.criware.jp/manual/native/adx2/latest/criatom_samples_control_aisac.html)
