### ISSUE TITLE
リザルトUIのプレハブを作成する　

### ISSUE THREAD

**Issue by ShinoharaRyuga** [VGA-Team2022/idol-road#129]
```yaml
start_date: 2022/12/8
due_date: 2022/12/9
progress: 0.1
parent: 0
```

関連資料
https://docs.google.com/spreadsheets/d/1FAagF6nKZKZE3hG78oxwmmTXFhUbjzq6/edit#gid=1605299737&range=A1:F2
（完成図に目を通して下さい。矢印の右側のイラスト）

使用して欲しいプレハブはAssets/Prefabs/UIフォルダ内の**ResultUI**です。
●ResultUIに以下のテキストを追加して欲しいです。
・結果を表示するテキスト
・BAD、GOOD、PERFECT、SUPERPERFECT、の各数を表示するテキスト

●作成して欲しい機能
・テキストに結果を反映する機能
・反映時のアニメーション [こんな感じのやつ](https://gyazo.com/898cf83d9c1d6ad7fdc9d408383d24f8)
機能を追加するクラスは**ResultUIController**です。

よろしくお願いいたします。
