### ISSUE TITLE
ステージ選択UIを作成する

### ISSUE THREAD

**Issue by ShinoharaRyuga** [VGA-Team2022/idol-road#140]
```yaml
start_date: 2022/12/8
due_date: 2022/12/13
progress: 0.1
parent: 0
```

仕様が変更されたのでそちらを作成する。
