### ISSUE TITLE
ゲームシーン（背景）の作成

### ISSUE THREAD

**Issue by ShinoharaRyuga** [VGA-Team2022/idol-road#36]
```yaml
start_date: 2022/11/21
due_date: 2022/11/27
progress: 0.1
parent: 0
```

関連資料
[レイアウト](https://docs.google.com/spreadsheets/d/1FAagF6nKZKZE3hG78oxwmmTXFhUbjzq6/edit#gid=1404509300)

関連資料を参考にUIを作成して下さい
