### ISSUE TITLE
スーパーアイドルタイムの機能を作成

### ISSUE THREAD

**Issue by ShinoharaRyuga** [VGA-Team2022/idol-road#43]
```yaml
start_date: 2022/11/24
due_date: 2022/12/8
progress: 0.1
parent: 0
```

関連資料
https://drive.google.com/drive/u/0/folders/1O4vFe9TOdMstvEsSIDMWFox7GTb-Nw73

関連資料を参考に作成よろしくお願いします。
