### ISSUE TITLE
敵が吹き飛ぶ際のSEを追加する

### ISSUE THREAD

**Issue by ShinoharaRyuga** [VGA-Team2022/idol-road#49]
```yaml
start_date: 2022/11/21
due_date: 2022/11/29
progress: 0.1
parent: 0
```
