### ISSUE TITLE
敵のファンサを表示する

### ISSUE THREAD

**Issue by ShinoharaRyuga** [VGA-Team2022/idol-road#70]
```yaml
start_date: 2022/11/24
due_date: 2022/11/29
progress: 0.1
parent: 0
```
吹き出しについて確認する
