### ISSUE TITLE
リザルト条件の作成

### ISSUE THREAD

**Issue by ShinoharaRyuga** [VGA-Team2022/idol-road#71]
```yaml
start_date: 2022/11/21
due_date: 2022/12/8
progress: 0.1
parent: 0
```

関連資料
https://docs.google.com/spreadsheets/d/1FAagF6nKZKZE3hG78oxwmmTXFhUbjzq6/edit#gid=1566841873

**Comment by ShinoharaRyuga** [comment]
start_date: 2022/11/19
due_date: 2022/11/19
progress: 0
parent: 0

**Comment by ShinoharaRyuga** [comment]
```yaml
start_date: 2022/11/19
due_date: 2022/11/19
progress: 0.1
parent: 0
```
