### ISSUE TITLE
ガントチャート　テスト

### ISSUE THREAD

**Issue by ShinoharaRyuga** [VGA-Team2022/idol-road#76]
```yaml
start_date: 2022/11/19
due_date: 2022/11/19
progress: 0.1
parent: 0
```
