### ISSUE TITLE
強欲ステージの作成

### ISSUE THREAD

**Issue by ShinoharaRyuga** [VGA-Team2022/idol-road#78]
```yaml
start_date: 2022/11/26
due_date: 2022/12/8
progress: 0.1
parent: 0
```

関連資料
https://docs.google.com/spreadsheets/d/1FAagF6nKZKZE3hG78oxwmmTXFhUbjzq6/edit#gid=52382503
