### ISSUE TITLE
ファンの生成間隔を変更できるようにする

### ISSUE THREAD

**Issue by ShinoharaRyuga** [VGA-Team2022/idol-road#80]
```yaml
start_date: 2022/11/21
due_date: 2022/11/27
progress: 0.1
parent: 0
```

7.68秒ごとにファンが生成されています。←BPMに合わせて生成を行っているから。
この生成間隔をランダムにして欲しいです。
BPMには合わせたいので以下の時間のいずれかを選択し、生成を行って下さい。

生成時間
7.68秒
5.76秒
3.84秒
1.92秒

例　7.68秒→3.84秒→5.76秒→3.84秒→1.92秒・・・
