### ISSUE TITLE
BGMを同時に再生する

### ISSUE THREAD

**Issue by ShinoharaRyuga** [VGA-Team2022/idol-road#81]
```yaml
start_date: 2022/11/21
due_date: 2022/11/24
progress: 0.1
parent: 0
```
