### ISSUE TITLE
ゲームの一連の流れを作成する

### ISSUE THREAD

**Issue by ShinoharaRyuga** [VGA-Team2022/idol-road#82]
```yaml
start_date: 2022/11/21
due_date: 2022/12/3
progress: 0.1
parent: 0
```

タイトルシーン→難易度選択シーン→ゲームシーン→リザルトシーン→タイトル

上記の一連の流れを作成してください。
シーン遷移にはフェードイン・フェードアウトを入れてください。
