### ISSUE TITLE
アイテムを取得できるようにする

### ISSUE THREAD

**Issue by ShinoharaRyuga** [VGA-Team2022/idol-road#83]
```yaml
start_date: 2022/11/21
due_date: 2022/11/22
progress: 0.1
parent: 0
```
