### ISSUE TITLE
評価別のファンの吹き飛び方を作成する

### ISSUE THREAD

**Issue by ShinoharaRyuga** [VGA-Team2022/idol-road#91]
```yaml
start_date: 2022/11/21
due_date: 2022/12/8
progress: 0.1
parent: 0
```

関連資料
https://docs.google.com/spreadsheets/d/1FAagF6nKZKZE3hG78oxwmmTXFhUbjzq6/edit#gid=713393304
